#------------------Merchants-----------
### admin
POST http://localhost:3000/merchants
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDQyYTUyYzcwZjVmYjEyOWExY2ZiNDkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2ODIwODkyNjB9.nuPfxNhBMUFV3xuq2k7n63fiOY6kKixlJ62qayGjQLM

{
    "name": "McDonalds",
    "CIF": "mac123456",
    "address": "Gran via 38",
    "email": "mcsonalds_granVia@comida.com",
    "phone_num": "+34 123 456789"
}
### admin
PUT http://localhost:3000/merchants/64464d6b7a32395ca884175b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDQyYTUyYzcwZjVmYjEyOWExY2ZiNDkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2ODIwODkyNjB9.nuPfxNhBMUFV3xuq2k7n63fiOY6kKixlJ62qayGjQLM

{
    "name": "BurgerUpdateado2",
    "CIF": "burger123456",
    "address": "Gran via 57",
    "email": "burger_granVia@comida.com",
    "phone_num": "+34 123 456798"
}
### admin
GET http://localhost:3000/merchants
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDQyYTUyYzcwZjVmYjEyOWExY2ZiNDkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2ODIwODkyNjB9.nuPfxNhBMUFV3xuq2k7n63fiOY6kKixlJ62qayGjQLM

### admin
GET http://localhost:3000/merchants/644657f568134591903d9787
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDQyYTUyYzcwZjVmYjEyOWExY2ZiNDkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2ODIwODkyNjB9.nuPfxNhBMUFV3xuq2k7n63fiOY6kKixlJ62qayGjQLM

### admin
DELETE http://localhost:3000/merchants/644657e368134591903d9778
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDQyYTUyYzcwZjVmYjEyOWExY2ZiNDkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2ODIwODkyNjB9.nuPfxNhBMUFV3xuq2k7n63fiOY6kKixlJ62qayGjQLM








#----------------------------Users-----------------------
### public user
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "name": "Sebastian usuario 2",
    "email": "sebastian2@test.com",
    "password": "sebastian2123",
    "age": 22,
    "city": "barcelona",
    "interests": ["musica", "fiesta"],
    "acceptRecievingOffers": true
}

### registered user
PUT http://localhost:3000/users/
Content-Type: application/json

{
    "name": "Sebastian Nuevo3",
    "email": "sebastian@test.com",
    "password": "sebastian123",
    "age": 21,
    "city": "madrid",
    "interests": ["comida", "deportes", "ocio"],
    "acceptRecievingOffers": false
}
### registered user
DELETE http://localhost:3000/users/
Content-Type: application/json

{
    "email": "sebastian2@test.com",
    "password": "sebastian2123"
}
### merchant
GET http://localhost:3000/users/madrid
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDQ2NTdmNTY4MTM0NTkxOTAzZDk3ODMiLCJyb2xlIjoibWVyY2hhbnQiLCJpYXQiOjE2ODIzMzE2Mzd9.jdRp7TqVvod9_CqGNJEQCWYlnPbeDEokRJbLqODQAPE







#--------------------------Webpages----------------------------
### merchants
POST http://localhost:3000/webpages
### merchants
PUT http://localhost:3000/webpages/id
### merchants
POST http://localhost:3000/webpages/photos
### merchants
POST http://localhost:3000/webpages/texts
### merchants
DELETE http://localhost:3000/webpages/id

### users public and registered
GET http://localhost:3000/webpages
### users public and registered
GET http://localhost:3000/webpages/id
### users public and registered
GET http://localhost:3000/webpages/search/city
### users public and registered
GET http://localhost:3000/webpages/search/city/activity

### registered users only
PATCH http://localhost:3000/webpages/id

















# token admin: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDQyYTUyYzcwZjVmYjEyOWExY2ZiNDkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2ODIwODkyNjB9.nuPfxNhBMUFV3xuq2k7n63fiOY6kKixlJ62qayGjQLM
# token mcdonalds: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDQ2NTdmNTY4MTM0NTkxOTAzZDk3ODMiLCJyb2xlIjoibWVyY2hhbnQiLCJpYXQiOjE2ODIzMzE2Mzd9.jdRp7TqVvod9_CqGNJEQCWYlnPbeDEokRJbLqODQAPE
# webpage_id mcdonalds: 644657f568134591903d9785
#merchant id mcdonalds: 644657f568134591903d9787
# user id mcdonalds: 644657f568134591903d9783






# {
#     "name": "McDonalds",
#     "CIF": "mac123456",
#     "address": "Gran via 38",
#     "email": "mcsonalds_granVia@comida.com",
#     "phone_num": "+34 123 456789"
# }

# {
#     "name": "BurgerKing",
#     "CIF": "buger123456",
#     "address": "Gran via 57",
#     "email": "burger_granvia@comida.com",
#     "phone_num": "+34 975 456789"
# }